### ISSUE TITLE
scripts directory deleted by something

### ISSUE THREAD

**Issue by springmeyer** [BergWerkGIS/mapnik-dependencies#22] opened 2015-02-11 01:35 UTC
@BergWerkGIS - trying to run the scripts to create a new Mapnik 3.x SDK I hit a couple problems:

 - zlib vc11 directory did not exist (this could be fixed by removing the package/zlib directory so a new version was fully downloaded that contained the vc11 directory
 - then I completely removed the `packages` directory manually and then ran `scripts/build.bat` and hit this:

![screen shot 2015-02-10 at 5 32 37 pm](https://cloud.githubusercontent.com/assets/20300/6140321/19cd0c70-b14b-11e4-80a6-3617631d94cb.png)

What happened is that the build got all the way to mapnik without error but then something deleted the `scripts` directory - obvious the build failed because of this.

**Comment by springmeyer** [comment] 2015-02-11 01:37
ah, what happened is that something checked out `master` branch and because the scripts are the in windows branch only they dissapeared. So some git clone and git checkout is failing somewhere. We should also move the scripts to the master branch and get rid of the `windows` branch as a prevention against this too, sound good?

**Comment by springmeyer** [comment] 2015-02-11 01:39
also found that `packages/mapnik-master` was empty.

**Comment by BergWerkGIS** [comment] 2015-02-11 07:45
* Branch `windows` merged into `master` and deleted.
* Couldn't reproduce the `scripts` dir problem, ran thru without problems.
* Empty `mapnik-master` dir was due to using branches `memory-fix` for `node-mapnik` and `mapnik-gyp`.
  * `settings.bat` is more verbose now and echos the branches used

Running the whole build again ATM, as I forgot to switch to `master` branches before.

**Closed** 2015-02-11 07:45 UTC
